apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: multi-tenancy-gitops
    group: pipeline
    type: git
  name: gitops-repo
data:
  branch: ocp47-2021-2
  host: github.com
  org: gitops-mq-demo
  owner: gitops-mq-demo
  parentdir: .
  protocol: https
  repo: multi-tenancy-gitops-apps
  url: https://github.com/gitops-mq-demo/multi-tenancy-gitops-apps.git
