apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: artifactory-access
  namespace: ci
spec:
  encryptedData:
    ARTIFACTORY_ENCRYPT: AgCIwr3mINe7SOKcXs/M0J0sOUmEslh8qLTWZ6M02OSJScv71g8pChot0ag1sYtovTwv+xYHHGz3R+Ri0sR118zBXNJcaNW3tNMlJDeYpq0raOaE6EPPSRKhx+V3zT/TAU+0KwqFk2Ja2NWUnYauPorj52226ooawtXM0QpB+R6Kf1Fkw3yx5esfub3Euv30ZOwMq27+QC/xf8o7+D2bfyM49FEhaLbJzxhBuG0SE+qHHTpJy7piMmvPP/u5lgFPg6tASfcL5SxDaTtUdg41KaomDNEjFkKylJ2//FmlLJrbE0Xdocr1YpBhO6r9jQ3EObhqDEm3IHZbxC5m212yQHkDQ7SYZKYbXVZ8gfm5bEqRi6YI37k63BJzelV/JkBL/w8MHM1ukFVLDEqV7vFTujeIAjgoRLLWfRB9bRq+w1Blhg4ubXj0cugGnFElaezjMHZxtwJtsbp9uKpUAlj1w5AQHzVPGbpr3YC1NORKJV1sClHlOtvTyAnj8Ap0qhFAIpNw9ZKfM8yRh7dyPQmt+YEXNUpX6fZRMP+O7eUyiTQZKEWhDcu/CitDuRsd5/LJCN1Co6zrIH62U/30Lf5G3T9Rs0x1QPcl0oF009AIKo6EiMfBF+aRyYaQodOatvTAETm2Q18SwvR+B0O1Cb3aJiTEjkDmHDJkyiTFfeyO/W7HY+N/puY2XWt1i0kK57KEz/SGja9MPcAv0K5dJK7cvVsGxR/atTjvp+79RqPNb1MVv8aizd/YcQ==
    ARTIFACTORY_PASSWORD: AgBuUxWRsXKmd74n9Vz+BXxzGr0+mkgE8qY9ToeucVBHZF6oAg9tEYw/0Aery9/FikdDtwHU3Z5PvujvmpBeWcxQQqd/th0Wt6F+pQ2PU+IR/actqNrmO65pSLq2zU3CvsYKrLOVEQ+5PYEwyW3qgoHFhzvEmc64MoWaGscBEk7knmFHDgXoTSPe9kBHiStqyV9TVCVutk3jaer8Zj9+lYkwMmD4MNDxVzKFzNLmC48htofHe2QLon+3a1IA663VFhxJJXU6MDew2FsMpn36l89dorZXUiKnu7TlA+5KQnHA+JxHyMhVt17ahbBiDcDxqNhS22O5NexXD3I67sz43hHTbizkhuEu6+qXcZUGKRLBAK+mjhiyKAPCzOH9eMH1mN8bZWehITx44Azwl8jdch4QLGJTgeKZyztMmevMC6u7F4pQPuLxL+FIJbMtG+JGau5n8ouu0FnDwFu+OGuHyAaFg+mYSZzeS2rAwRgEqfYhRHtb4xKKwWdPTZvpoekbCvG0YXaGERi0gO0+7EPbOZrjDR472BI/nEGvxwx6AGoA+IolAsZjl3MAdmLewIIWrjKz9RFzC7E4+RjsM6WXKx1SfIAxohx9+ApfCuY2DYkl0Mym2yLEV4/RNpCkbgndH2751pEHIMpjXJn08p5BhVVjRPUyDUvIDGz++HneGqKdR4TfRczwglydJbKPlfReo/4uAiWfKmoykVORJrpfcYjWW/hbpw==
    ARTIFACTORY_URL: AgClg021mGcqyR9G5mUMHyzW0tBxB05cF1dKvpr34jxZrxcN+uqA0bOSdaZ39sS1r4pFcdqG1mV/5lFhgm0DMtDO2oosd8eovYSfRH2Wlxlg0dR9TFm4Un3gXwbC3gR0UXqYFOHOwv9QbtD9PdLWQNKs/r243lOj3sijjAhs06bVJGrCKy4uEFmtGEHuNY+iR3Rrw1hItcE+/0GXzJpWKMneOm+3oFFShZH+cV/rsVmDWPYKbP83AI9Ncrb/r4+rkAmaZnYpUmtz3AGtznz+ZDD8Yo90B/Ag2hMhI0QrjV4X5CDoDZw/QP6NMq7R9pwg0JMmAT1HIYV14CqAwLwF9VxC3HsjfHVFGjvcb+YfWs+sZ7wSVSxN7Z4VIsygAxhiIm/KTSRQcgfT9aHR+3fI4+3PtsVnPoNnP02NmHJrzfAkeblkwSr00C30AtWkak6bYYGHpP4uXdFPvPu0CNHJN0H+AvTaYliYoTfxV1d9l8P1glf2fp5/saQ+lP3cVHUSi6YMLg+CMUsc/k0SOB9ke5O3kPxXDLKbra8hyGzeqECyDbz+9PVPlb6isCGVQUJOOWbWigk7VLSR0jco6bdOpvyHfFmwbl5Df5+KWvTUNsk6QctsAp82h8rTe4ybaikNh/Zx8fPpjVd64mcUl9Sjtwzg67SUvklBxC2F7zeNxuSj/1Cp3BJDBvA6xF7yFgt76w23vhANt1TU3tGKPSd8sVmDCZ/1T/ubyMMz79vqMumBE8pk+BusoGyIjA==
    ARTIFACTORY_USER: AgBI+Z0Bfpm3FPOVhftreSdriTbnNF9MFnTAFA29hy+SurP89L6javQbqAD8SBsKQrOs6bPcb1J0dPIyquiq7drg1Gnf2jsKHJ7WtacZj3SiGx5VJnM+LE09X+8cgXcGczQMpK4Jrp3TBW7Vr53OfqttKMROyvfAiEnZOEgXYUenqP6PKAhwwuKnY0rbIC1DOMMuZwcFs+ctnueiXWMEsSnhbI6Mc6BtfwC4zgl7JAh1c5yPFI2vzxB0suJiqPY29G8jQPqJXBpIILOeTYetuuGSpqBS+7BfTuOMkF+mlWmA401ZNxS6EXUShmkR94iG0MPJagrzo52G4t5qK3xJ7OtD0I++Ihd81xE/DQj6lmIbVq5RAXLvz7/D9YcPBnAc3fC3AU3AjakPGzrDdPLnMEAKJP7WeS2QxlwSd+x/Kt5EhCDoJ8PPPuY1a0y3bDjdq9vUzyPbgZYvbQ9Qdhuj0NdAy+p7vWUiX/IDRtJV77ZWTkAZg9sfOr7or6OyaUtI5Q2nDdZHED+DyUXdELfnjH0QcAQkE07REZeEQrHrJIjmJgChZubJXpel1mcbJPHSH03DMdnqyN2MolKHNMFqyJ+nPwwYQh9zkbLB2ntGPxnYKJL+1NzsA0TrzsHjcnQOTca8UYHh7bpqCLkM8DXI/XnfnmYUe4bRZ5wwrwj3Lc4v1Up5Rz5xYuh3qOlc9QCEslyhIZ8OhQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:ARTIFACTORY_URL: {}
            f:ARTIFACTORY_USER: {}
          f:type: {}
        manager: kubectl
        operation: Update
        time: "2021-09-07T18:22:24Z"
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            f:ARTIFACTORY_ENCRYPT: {}
            f:ARTIFACTORY_PASSWORD: {}
        manager: unknown
        operation: Update
        time: "2021-09-07T18:23:13Z"
      name: artifactory-access
      namespace: ci
    type: Opaque

