apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: git-credentials
spec:
  encryptedData:
    password: AgCLjNITD6u0SrEOEo9SzqGYwaj1oi9KLLUBHG+4WoceV7k/J/ciykAKRfZvgXp78zRTJXLwe1B/ISAB2BJbV6eZ9wGgHRWT6H96vwXjPEi93vxjkT26jLpZ/RSTUM3p1I5LTi5VCbzxbaa0zBLIx6k63/gKiIRz5P3OjqAGIVNwCmg0UkiUhbQVgnCdB3AG1DQAT6hub6MPMv/6zzz3QPIknY/gV3g0HT3geYQgOlJWNyX3BH4PnyKD8I9sla3mvUVXAXfqhUTstKdsaoTLV1YSXr6hZSvPOUZ4AoSVA4niFflXy78eFX9jpYqmNuPLoms3i1L+k3BaAGHv8LcFQQZJYy92jYUx3DWnk5pq8B5IsY5xtc3r4fVaROHShOvyEojpERZaK7Sm5OVE92ROBP0s7jV9ZhNcme9A1gqEvJFpJfMqpcTUR5DsMqheqELi3oT9LcL0PdprqzAduVgLxNFwEYLTc812bChXfnRkHM19qggUY0NmGE4s31KDU8toc27b9ZF0MkYjFmiC6lHG4CeRBdXWipkPX0hsF1FAyd7btIrtFrQ5w7khPKYKK+mpfXUq0Ia/RmuNtDC4TwvhvV4rVMoAjQl5mwgaK4VTfrFO9w9lxpey93u6p23vTHSEudtwkIA/yawYeL0sTgthxr0LIkh3SiHLHpo52Ot9LPT36YMWq9JTzw3WtNRGX7IMZ2etfSC3wsNWGLcOtGp7B6erVDzviukFd+fG3qkI0OVYEKXor9ogdPCz
    username: AgCoKot1eKgZkZnUkykpmUsXUMY/ToegqvwF1cqblTOY3/9xOzpxS3BJFwMPfgddMsxL7k5kRlIqpNSBcjgL27TgeGYAlQmoql6zmf1r629Yoh1FcP7QsgzbQsZPdk+LkFneJunGq/1DAm7oylK949mEl9pFt6bXX8d86dy/52AmRYGORDaeV5CWiDx4UzQdICUEbOUgQeWcl7phlGg847otwjb1YXWypsOqlUIH7f+bxfXRRnEYfHGrekh65DINAgIwkJcjwsFy2VD+3vTEparQU1xjwLvVhNTbHIvd9uzG2A7rHD66uHk+kWpMB5j7ydZrhdDv8YH6JPxAnK8Ew1oOv7k24eBGPINe6+I+KsduR05xppi7sUIxX57qW6AC3xi2+BWLNfE76NUNaSwXCoPNcpPhACQmZAHyX6lIa9Pzf7rEH7VBif17KsGeCRYRM7p6Qw+GxBzylFt0uw/krlmM26UZQ0BBdffGiFpIk0Q+582MzkoLRGs3Of5Eoror1y21qdLbsIVdRH/3TdqEVrhjFo1/Rc5mLTf3jYHe23YTv2eCrNqSIRXnNn69J60tNPv2Zf8MjBnagESXKmPsKcJJQG6ygM31gnq+7y/FxtEercV+1yVaqNzZv9crIV7SY5fk00yO55D9HVrkvG+/g9fnntEFPMpK52Ooafu8yYmZS9B/92jkDmSAFbG8fs4zuqbjbTet8BmZ
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
    type: kubernetes.io/basic-auth

